### ISSUE TITLE
Error publishing

### ISSUE THREAD

**Issue by simongis** [Esri/network-analysis-services#13]
I have ESMP 2016 R1 for Asia Pacific with a full license, and have already published geocoding services and registered with ArcGIS Enterprise 10.5 (federated, all on one machine, domain certificates applied)

I am now trying to run through these steps to publish the network-analysis-services, but hit what I hope is a  trivial issue when publishing:

- Routing_ND located in this GDB:
![image](https://cloud.githubusercontent.com/assets/2769383/21835027/e0decbf6-d80d-11e6-93b4-d23c5f9c9821.png)

- Created an empty folder for the SD files:
![image](https://cloud.githubusercontent.com/assets/2769383/21835051/158bc39a-d80e-11e6-8208-7a45d7f2f76c.png)

- Logged into ArcMap as a portal admin (portaladmin)
- Have the 10.5 tools downloaded to D:\ESMP\network-analysis-services-2.0

- Settings when running the tool:
![image](https://cloud.githubusercontent.com/assets/2769383/21835198/342bf26a-d80f-11e6-80b0-d83bb0a49c16.png)

Error:
![image](https://cloud.githubusercontent.com/assets/2769383/21835202/3e65d066-d80f-11e6-93d2-bd2d10d0a1af.png)

This is whilst I am logged into the portal in ArcMap as portaladmin.
PublishRoutingServices.log never gets created.

Any suggestions? I am sure it is something small I have missed.

**Comment by deelesh** [comment]
- Can you check if your federated ArcGIS Server is indeed federated with the portal running at `https://lap-304261.services.esriaustralia.com/arcgis` or it is federated with some other portal?
 
You can check the above by running the following python code from within the Python Window in ArcMap. Before running the code, make sure you are signed into the portal as an admin user (`portaladmin` in your case) from within ArcMap.

```python
import arcpy
import requests
active_portal_url = arcpy.GetActivePortalURL().rstrip("/")
rest_info = requests.get("https://lap-304261.services.esriaustralia.com:6443/arcgis/rest/info?f=json", verify=False).json()
owning_system_url = rest_info.get("owningSystemUrl", "NOT_FEDERATED")
print("Active Portal URL: {}".format(active_portal_url))
print("Owning System URL: {}".format(owning_system_url))
```
Can you send me what the above code prints?

**Comment by simongis** [comment]
Can confirm it is federated and all on one machine:
```
Active Portal URL: http://lap-304261.services.esriaustralia.com.au/arcgis
Owning System URL: https://lap-304261.services.esriaustralia.com.au/arcgis
```

![image](https://cloud.githubusercontent.com/assets/2769383/21914445/83a93874-d987-11e6-9460-e60f5ce697d3.png)

**Comment by deelesh** [comment]
The PublishRoutingServices tool is doing a string compare between Active Portal URL and Owning System URL values which is returning false in your case as the Active Portal URL is using `http` and owning system url is using `https`. You cannot change the owning system url. But you can change the active portal url by starting the ArcGIS Administrator application and changing the URL for your portal to be `https://lap-304261.services.esriaustralia.com.au/arcgis`

Also once you get this issue fixed, you will run into another error since the value for the `Server Data Folder Path` parameter in your screenshot is not correct.  The value should not include the name of the geodatabase containing the network dataset. It should just be the folder containing the geodatabase which in your case will be `D:\ESMP\StreetMap_Data`

**Comment by simongis** [comment]
Perfect.  Thanks for troubleshooting this.  Issue can be closed.

![image](https://cloud.githubusercontent.com/assets/2769383/21967586/3e727294-dbde-11e6-962c-3e0cc35172b3.png)

**Comment by deelesh** [comment]
Thanks for the feedback. Closing the issue
