### ISSUE TITLE
Geoprocessing error when publishing

### ISSUE THREAD

**Issue by selsoz** [Esri/network-analysis-services#14]
I am getting a geoprocessing error when I run the "publish routing services" script.  It gets as far as trying to create a map service definition then fails - the error message in the log file is:

"ERROR 001272: Analyzer errors were encountered (codes = 147, 147, 147, 147).
Failed to execute (StageService)."

ArcMap results are below.

My service definition folder is sitting outside of the ESMP folder and my active portal url matches with my owning system url so I've ruled out those possibilities.

Any ideas of what I might be doing wrong?
 
![geoprocessingerror](https://cloud.githubusercontent.com/assets/24904665/22008714/abdbe74a-dcd1-11e6-9181-27f40d4bc67f.PNG)

**Comment by deelesh** [comment]
I would need to see the contents of PublishRoutingServices.log file to check what other parameter values were specified as input  and to also get an idea about the overall state of the publish routing services tool before the failure. The tool only outputs some messages in the tool progress dialog. But there are lot more messages in the PublishRoutingServices.log file.

Also since the failure is encountered when running StageService tool, I would like to see the contents of `D:\Data\EsriStreetMapPremium\ServiceDefinitionFiles` folder. So can you zip up the folder (and the PublishRoutingServices.log) and send it to me via email at dmandloi@esri.com

**Comment by selsoz** [comment]
Word of advice:  If anyone gets stuck like I did, don't assume the problem is with the script.  Think outside of the box! :-)  

I thought I had licensed network analyst extension on ArcGIS Server at time of install.  Apparently not.  Unfortunately the error message I received did not point me to a licensing issue and only discovered the problem when I tried to publish the service manually from ArcMap (rather than using the script).  The "Analyze" results is a good way of spotting such problems.

Deelesh has informed me that the publishroutingservices tool can check for the presence of the network analyst license on the server so the plan is to add this check in a future release.

Thanks Deelesh for your help.  This issue can now be closed.
